services:
  apachedjango:
    build: .
    ports:
      - "8080:80"
      - "8000:8000"
    volumes:
      - ./www:/var/www/map
      - ./servidor/ehuvpf:/var/www/ehuvpf
      - ./ehuvpf-projects:/var/lib/ehuvpf/ehuvpf-projects
    command: apachectl -D FOREGROUND
    environment:
      QT_QPA_PLATFORM: offscreen
      TZ: Europe/Madrid
  db:
    image: mysql:8.3.0
    user: root
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - ~/db-data:/var/lib/mysql

secrets:
  db_root_password:
    file: ./.secrets/db_root_password.txt
