services:
  apachedjango:
    build: .
    ports:
      - "8080:80"
      - "8000:8000"
    volumes:
      - ./www:/var/www/map
      - ./servidor/ehuvpf:/var/www/ehuvpf
      - ./ehuvpf-projects:/var/lib/ehuvpf/ehuvpf-projects
      - /etc/letsencrypt/live/ehukhivpf.com/fullchain.pem:/etc/letsencrypt/live/ehukhivpf.com/fullchain.pem
      - /etc/letsencrypt/live/ehukhivpf.com/privkey.pem:/etc/letsencrypt/live/ehukhivpf.com/privkey.pem
    command: apachectl -D FOREGROUND
    environment:
      QT_QPA_PLATFORM: offscreen
      TZ: Europe/Madrid
  db:
    image: mysql:8.3.0
    user: root
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - ~/db-data:/var/lib/mysql

  tiles:
    image: overv/openstreetmap-tile-server
    ports:
      - "8081:80"
    volumes:
      - ~/osm-data:/data/database
    command: "run"

secrets:
  db_root_password:
    file: ./.secrets/db_root_password.txt
