[package]
name = "esri_a_geojson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lector_esri = { path="../lector_esri" }
